BEARER_TOKEN = "YOUR_BEARER_TOKEN"
API_KEY = "YOUR_API_KEY"
API_SECRET = "YOUR_API_SECRET"
ACCESS_TOKEN = "YOUR_ACCESS_TOKEN"
ACCESS_TOKEN_SECRET = "YOUR_ACCESS_TOKEN_SECRET"
INTERVAL = 60  # Interval in minutes. Default is 60
